apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-rwx-bootstrap
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: onap
  source:
    repoURL: https://git.example.com/repo.git
    targetRevision: main
    path: longhorn-rwx-bootstrap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
